version: "3"

services:
  web:
    image: "pegasus-web:${RELEASE_TAG}"
    build:
      context: .
      dockerfile: docker-nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"